### ISSUE TITLE
Can we change the display name

### ISSUE THREAD

**Issue by jekayode** [yabacon/paystack-whmcs#1]
Can the name here be changed to simply 'PayStack'?

![paystack](https://cloud.githubusercontent.com/assets/18671013/15894310/19a8d1ac-2d7d-11e6-8065-e9ffd7a123e6.png)

Regards

**Comment by ibrahimlawal** [comment]
@jekayode thanks. yes you may. We do prefer that you let it be clear to your customers that choosing the option means they want to pay with a card. So, perhaps you could go with `Pay with ATM card`. Just edit the `FriendlyName`.
